server.port=8081
spring.application.name=api-gateway

logging.level.org.springframework.cloud.gateway=TRACE
cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000,http://localhost:4200}