spring.application.name=TicketFlow
spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.open-in-view=false

springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.admin.default.email=${ADMIN_EMAIL:admin_local@ticketflow.com}
app.admin.default.password=${ADMIN_PASSWORD:123456}